### PR TITLE
Fix comment error or typo

### PR DESCRIPTION
**Pull request by googs1025**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it
fix some typo or comment error
#### Which issue(s) this PR fixes

Fixes #

#### Special notes for your reviewer
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by kerthcet — COMMENTED** [review]
/ok-to-test
/lgtm
/approve

Thanks!

**Comment by googs1025** [comment]
@kerthcet thanks! Is there something wrong with the e2e test? I looked at the log errors.

**Comment by kerthcet** [comment]
Will be fixed by https://github.com/kubernetes-sigs/lws/pull/79

**Pull request merged**
