### PR TITLE
Unify Leader Election Namespace with Deployment Namespace

### LINKED ISSUE #262: Failed install in a different namespace
**What happened**:
I want to install lws in namespace `lws-test` and flow these steps:
1. change the kustomization.yaml namespace field as:
    namespace: lws-test
   change the manager_auth_proxy_patch.yaml as well:
  - name: manager
    args:
    - "--namespace=lws-test" 
2. `make artifacts`
3. Replace the image in the manifest.yaml generated by the "make artifacts" command with gcr.io/k8s-staging-lws/lws:main.

After I applied the manifest.yaml, I got the following error:
> 2024-11-21T02:35:24Z    INFO    setup   both healthz and readyz check are finished and configured
2024-11-21T02:35:24Z    INFO    setup   starting manager
2024-11-21T02:35:24Z    INFO    setup   waiting for the cert generation to complete
2024-11-21T02:35:24Z    INFO    controller-runtime.metrics      Starting metrics server
2024-11-21T02:35:24Z    INFO    starting server {"name": "health probe", "addr": "[::]:8081"}
2024-11-21T02:35:24Z    INFO    controller-runtime.metrics      Serving metrics server  {"bindAddress": "127.0.0.1:8080", "secure": false}
2024-11-21T02:35:24Z    INFO    cert-rotation   starting cert rotator controller
I1121 02:35:24.113143       1 leaderelection.go:254] attempting to acquire leader lease lws-system/b8b2488c.x-k8s.io...
2024-11-21T02:35:24Z    INFO    Starting EventSource    {"controller": "cert-rotator", "source": "kind source: *v1.Secret"}
2024-11-21T02:35:24Z    INFO    Starting EventSource    {"controller": "cert-rotator", "source": "kind source: *unstructured.Unstructured"}
2024-11-21T02:35:24Z    INFO    Starting EventSource    {"controller": "cert-rotator", "source": "kind source: *unstructured.Unstructured"}
2024-11-21T02:35:24Z    INFO    Starting Controller     {"controller": "cert-rotator"}
E1121 02:35:24.115017       1 leaderelection.go:436] error retrieving resource lock lws-system/b8b2488c.x-k8s.io: leases.coordination.k8s.io "b8b2488c.x-k8s.io" is forbidden: User "system:serviceaccount:lws-test:lws-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "lws-system"
2024-11-21T02:35:24Z    INFO    cert-rotation   no cert refresh needed
2024-11-21T02:35:24Z    INFO    Starting workers        {"controller": "cert-rotator", "worker count": 1}
2024-11-21T02:35:24Z    INFO    cert-rotation   no cert refresh needed
2024-11-21T02:35:24Z    INFO    cert-rotation   Ensuring CA cert        {"name": "lws-validating-webhook-configuration", "gvk": "admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration", "name": "lws-validating-webhook-configuration", "gvk": "admissionregistration.k8s.io/v1, Kind=ValidatingWebhookConfiguration"}
2024-11-21T02:35:24Z    INFO    cert-rotation   Ensuring CA cert        {"name": "lws-mutating-webhook-configuration", "gvk": "admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration", "name": "lws-mutating-webhook-configuration", "gvk": "admissionregistration.k8s.io/v1, Kind=MutatingWebhookConfiguration"}
E1121 02:35:27.106795       1 leaderelection.go:436] error retrieving resource lock lws-system/b8b2488c.x-k8s.io: leases.coordination.k8s.io "b8b2488c.x-k8s.io" is forbidden: User "system:serviceaccount:lws-test:lws-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "lws-system"
E1121 02:35:31.137997       1 leaderelection.go:436] error retrieving resource lock lws-system/b8b2488c.x-k8s.io: leases.coordination.k8s.io "b8b2488c.x-k8s.io" is forbidden: User "system:serviceaccount:lws-test:lws-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "lws-system"

This is because` leaderElectResourceNamespace` flag in `main.go` is default set `lws-system`. 
I think the `leaderElectResourceNamespace` flag might not need to be a separate flag; it could just match the value of the `namespace` flag.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Kubernetes version (use `kubectl version`):
- LWS version (use `git describe --tags --dirty --always`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by wqlparallel**
This commit removes the separate leaderElectResourceNamespace flag and directly assigns the namespace flag value for leader election. This ensures consistency by using the same namespace for deployment and leader election, simplifying the configuration.

#### What this PR does / why we need it
This commit removes the separate `leaderElectResourceNamespace` flag
and directly assigns the `namespace` flag value for leader election.
This ensures consistency by using the same namespace for deployment
and leader election, simplifying the configuration.
#### Which issue(s) this PR fixes

Fixes #262 

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by wqlparallel** [comment]
hi @liurupeng, do you have some time to review the code?

**Comment by kannon92** [comment]
I find this a bit difficult to use.

I am building a downstream operator to install LWS and I think users can specify namespaces to deploy.

So if someone does `operator-sdk run build BUILD_IMAGE --namespace lws-test`, the deployment will not work. One needs to patch the deployment to match the namespace they are deploying.

For Kueue/JobSet, we would take the namespace to be the location of serviceAccount of the respective operator. Could we do that instead?

**Comment by kannon92** [comment]
Sorry this is not the right PR.

**Comment by kerthcet** [comment]
Do you mean this one? https://github.com/kubernetes-sigs/lws/pull/226 @kannon92 And can you provide the related PR in kueue or jobset?

**Comment by kannon92** [comment]
Yeah, the PR was part of component config work for Kueue and Jobset. But the namespace was read from the service account rather than specifying it. U

**Pull request merged**
