### PR TITLE
Fix make generate error with invalid repo path

### PR DESCRIPTION
**Pull request by kerthcet**
fix https://github.com/kubernetes-sigs/lws/issues/13

### CODE REVIEW

**Comment by ahg-g** [comment]
how about changing things to lws instead? I guess here https://github.com/kubernetes-sigs/lws/blob/9af20f61ba6d4e4ebd97b43bfa6ffca5aa618743/PROJECT#L8-L9 and that should be reflected in all other autogenerated stuff https://github.com/search?q=repo%3Akubernetes-sigs%2Flws%20%22leader-worker-set%22&type=code

**Comment by kerthcet** [comment]
That's what came to my mind first - **Changing leader-workder-set to lws**, however, I think we have to change all, more than a part, maybe the test-infra as well?

**Comment by ahg-g** [comment]
The test-infra seems aligned with lws: https://github.com/kubernetes/test-infra/pull/32081/files

**Comment by kerthcet** [comment]
SG then.

**Comment by kerthcet** [comment]
In favor of https://github.com/kubernetes-sigs/lws/pull/11.
/close

**Pull request closed without merging**
