### PR TITLE
Remove maxSurge

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it

Prepare for release 0.2.0

#### Which issue(s) this PR fixes

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by kerthcet** [comment]
I believe the flaky test is mostly caused by https://github.com/kubernetes-sigs/lws/pull/101, details see https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_lws/107/pull-lws-test-integration-main/1780144581271097344

**Comment by googs1025** [comment]
@kerthcet That's a bit strange. Currently, I have only added the eventRecorder without incorporating any other logic.

**Comment by kerthcet** [comment]
> @kerthcet That's a bit strange. Currently, I have only added the eventRecorder without incorporating any other logic.

The latest event changes after your pr, I guess this is the root cause.

**Pull request merged**
