### PR TITLE
Add executable permission to the example script ray_init.sh

### PR DESCRIPTION
**Pull request by xgchena**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it

The commit adds "x" permission to the vllm example script ray_init.sh . Without the permission, container startup fails due to error "sh: 1: /vllm-workspace/ ray_init.sh: Permission denied"

#### Which issue(s) this PR fixes

N/A. I was trying with the [vllm example](https://github.com/kubernetes-sigs/lws/tree/034a888b43d35509576cbf7bc0093a4ddc75300f/docs/examples/vllm) and found that containers failed to start, and logs show that the ray_init.sh was not executed due to permission issue, e.g.,

```
$ kubectl logs vllm-0  
sh: 1: /vllm-workspace/ray_init.sh: Permission denied
INFO 06-26 08:22:10 api_server.py:151] vLLM API server version 0.4.1
...
2024-06-26 08:22:13,143	INFO worker.py:1749 -- Started a local Ray instance.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 159, in <module>
    engine = AsyncLLMEngine.from_engine_args(
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 352, in from_engine_args
    initialize_ray_cluster(engine_config.parallel_config)
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py", line 106, in initialize_ray_cluster
    raise ValueError(
ValueError: The number of required GPUs exceeds the total number of available GPUs in the cluster.
```

With fix, the model is successfully deployed, and I managed to get inference from it, see below

```
$ curl http://localhost:8080/v1/completions \
-H "Content-Type: application/json" \
-d '{
    "model": "facebook/opt-125m",
    "prompt": "San Francisco is a",
    "max_tokens": 7,
    "temperature": 0
}'
Handling connection for 8080
{"id":"cmpl-d09542e84246481f97f2efb9d15ad2c7","object":"text_completion","created":1719391009,"model":"facebook/opt-125m","choices":[{"index":0,"text":" great place to live.  I","logprobs":null,"finish_reason":"length","stop_reason":null}],"usage":{"prompt_tokens":5,"total_tokens":12,"completion_tokens":7}}  
```

#### Special notes for your reviewer

N/A

#### Does this PR introduce a user-facing change?

N/A

### CODE REVIEW

**Review by kerthcet — COMMENTED** [review]
/ok-to-test

Please sign the CLA first, thanks!

**Comment by liurupeng** [comment]
@xgchena @kerthcet I didn't see any changes in the PR?

**Comment by kerthcet** [comment]
It add the permission just like `chmod +x`.

**Comment by liurupeng** [comment]
ah, I see!

**Comment by kerthcet** [comment]
Kindly ping @xgchena could you sign the CLA to make sure we're following the conduct of Kubernetes community? I believe it wouldn't take too much time, if you have any problem, feel free to ping/DM me. Thanks very much!

**Pull request merged**
