### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by kerthcet**
fix https://github.com/kubernetes-sigs/lws/issues/5

Also Add the Issue/PR templates. This is mostly inspired by kueue.

### CODE REVIEW

**Comment by kerthcet** [comment]
I guess you haven't joined the org yet, so no privilege?

**Comment by liurupeng** [comment]
> I guess you haven't joined the org yet, so no privilege?

yes

**Comment by kerthcet** [comment]
cc @ahg-g

**Comment by ahg-g** [comment]
the test is not passing though, should we fix that first?

**Comment by kerthcet** [comment]
> the test is not passing though, should we fix that first?

I'm digging.

**Pull request merged**
