### PR TITLE
chore: upgrade e2e kind version

### PR DESCRIPTION
**Pull request by googs1025**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it
- Currently we support k8s versions: v1.27, v1.28, v1.29, so our e2e test image should be upgraded to v1.29.1
- kind version 0.18 -> 0.22
#### Which issue(s) this PR fixes

Fixes #
None
#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by kerthcet** [comment]
Can we support 1.30 now, it's released.

**Comment by kerthcet** [comment]
That's mean you should add an e2e test of v1.30 to test-infra. I think you got what I mean as talked offline.

**Comment by googs1025** [comment]
> Can we support 1.30 now, it's released.
@kerthcet 
Kind has not been updated yet, the latest version is 1.29. Maybe we should set it as todo and wait for kind to be updated before updating.
https://github.com/kubernetes-sigs/kind/releases

**Review by kerthcet — COMMENTED** [review]
/lgtm
/approve

Make sense to me to catch the latest version as Kubernetes are backward compatible.

**Comment by googs1025** [comment]
> That's mean you should add an e2e test of v1.30 to test-infra. I think you got what I mean as talked offline.

I will submit PR in the next few days. @kerthcet

**Pull request merged**
